baseURL = "https://ajonelis.github.io/"
languageCode = "en-us"
title = "Andrew Jonenlis"
theme = "PaperMod"

[menu]
[[menu.main]]
name = "Research"
url = "/research/"
weight = 1
[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 2
[[menu.main]]
name = "CV"
url = "/cv/"
weight = 3

[params]
description = "Assistant Teaching Professor of Economics at Syracuse University"
author = "Andrew Jonelis"
